---
version: "3.8"

services:
  oursource:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/techeron/oursource:dev
    container_name: oursource
    environment: 
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}
    depends_on:
      - postgres

  postgres:
    image: bitnami/postgresql:16.1.0-debian-11-r18
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
